### ISSUE TITLE
Python 3.X gives a Syntax Error 

### ISSUE THREAD

**Issue by Windsplunts** [mdonnalley/pyGoogleSearch#1]
Trying to run ImportExportFunctions.py with Python3 (Python Version 3.5.0 from Homebrew) gives me a syntax error on line 13

![screenshot 2015-09-29 12 40 03](https://cloud.githubusercontent.com/assets/1868926/10171509/83095e06-66a8-11e5-8d5f-158c6506c6cb.png)

**Comment by mdonnalley** [comment]
Hey Irvin,

Thanks for reaching out with this. I had actually come across this this
morning, which has led me to fix a lot of issue that had gone unseen when I
tried to update the package to work on Python 3.5. I've just now uploaded
version 2.0.1 on PyPi which should be fully functional.

Let me know if you have any more issues or have any other feedback.

Thanks!

Mike

**Comment by Windsplunts** [comment]
It looks like you hit a few bugs I didn't get a chance to come across xD I'll get rid of the PR and test out this new version. 

Thanks for putting this library out, it's uber important for me! =D
